GET http://localhost:9092/acc/refresh
Accept: application/json

###
GET http://localhost:9092/acc/refreshAllFunds
Accept: application/json

###
GET http://localhost:9092/acc/refreshAllPosition
Accept: application/json

###