ck:
  driverClass: com.clickhouse.jdbc.ClickHouseDriver
  url: jdbc:ch://172.23.73.20:8123/quantx
  user: default
  password: 123456
spring:
  kafka:
    listener:
      type: batch
    bootstrap-servers: 172.23.73.20:9092
    consumer:
      max-poll-records: 500
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: '*'