ck:
  driverClass: com.clickhouse.jdbc.ClickHouseDriver
  url: jdbc:ch://172.19.216.37:8123/quantx
  user: default
  password: 123456
spring:
  kafka:
    listener:
      type: batch
    bootstrap-servers: 172.19.216.37:9092
    consumer:
      max-poll-records: 500
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer