rocketmq:
  name-server: 172.18.222.230:9876
ck:
  driverClass: com.clickhouse.jdbc.ClickHouseDriver
  url: jdbc:ch://172.18.222.230:8123/quantx
  user: default
  password: 123456
server:
  port: 9093