rocketmq:
  name-server: 192.168.145.246:9876
ck:
  driverClass: com.clickhouse.jdbc.ClickHouseDriver
  url: jdbc:ch://192.168.145.246:8123/quantx
  user: default
  password: 123456
server:
  port: 9093