rocketmq:
  name-server: 172.24.210.142:9876
ck:
  driverClass: com.clickhouse.jdbc.ClickHouseDriver
  url: jdbc:ch://172.24.210.142:8123/quantx
  user: default
  password: 123456
server:
  port: 9093