package io.futakotome.trade.dto.ws;

public enum MessageType {
    CONNECT,
    MARKET_STATE,
    KL_HISTORY_DETAIL,
    REFRESH_SUB,
    SUBSCRIPTION,
    TRADE_DATE,
    KL_HISTORY,
    PLATES,
    STOCK_IN_PLATE, //查板块下的股票
    STOCKS,
    STOCK_OWNER_PLATE, //查股票所属的板块
    CAPITAL_FLOW,
    CAPITAL_DISTRIBUTION,
    REHABS,
    SNAPSHOT,
    ACCOUNTS,
    ACC_SUBSCRIBE,
    ACC_POSITION,
    STOCK_FILTER,
    ACC_FUNDS,
    PLACE_ORDER,
    MODIFY_ORDER,
    HISTORY_ORDER,
    INCOMPLETE_ORDER,
    USER_GROUP,//自选股分组
    USER_SECURITY,//自选股列表
    SET_PRICE_REMINDER,
    GET_PRICE_REMINDER,
    IPO,
    STOCK_IN_PLATE_BY_MARKET,
    FINANCIAL_EARNING_MOVE,
    FINANCIAL_EARNING_PRICE_HISTORY,
    FINANCIAL_STATEMENTS,
    FINANCIAL_REVENUE_BREAKDOWN,
    ANALYST_CONSENSUS,
    RESEARCH_RATING_SUMMARY,
    RESEARCH_MORNINGSTAR_REPORT,
    VALUATION_DETAIL,
    VALUATION_P_S_LIST, //板块/指数成分股估值列表
    CO_ACTIONS_DIVIDEND,
    CO_ACTIONS_BUYBACK,
    CO_ACTIONS_STOCK_SPLITS,
    SHAREHOLDER_OVR,
    SHAREHOLDER_HOLDING_CHANGE,
    SHAREHOLDER_HOLDER_DETAIL,
    SHAREHOLDER_INSTITUTIONAL,
    INSIDER_HOLDER_LIST,
    INSIDER_TRADE_LIST,
    COMPANY_PROFILE,
    COMPANY_EXECUTIVES,
    COMPANY_EXECUTIVE_BACKGROUND,
    COMPANY_OP_EFFICIENCY,
    TOP_TEN_BROKERS,
    DAILY_SHORT_VOLUME,
    SHORT_INTEREST,
    INSTITUTION_LIST,
    INSTITUTION_PROFILE,

    RT_BASIC_QUOTE,
    RT_KL,
    RT_TICKER,
    RT_TIME_SHARE,
    RT_BROKERS;

    MessageType() {
    }

    @Override
    public String toString() {
        return this.name();
    }
}
