server:
  port: 9090
  servlet:
    context-path: /
spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: 983528987@qq.com
    password: ${email.password}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: true
  datasource:
    url: jdbc:postgresql://172.21.195.165:5432/quantx_3rd_futu
    username: postgres
    password: 123456
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  kafka:
    bootstrap-servers: 172.21.195.165:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 5
    consumer:
      max-poll-records: 500
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
ck:
  driverClass: com.clickhouse.jdbc.ClickHouseDriver
  url: jdbc:ch://172.21.195.165:8123/quantx
  user: default
  password: 123456
ft:
  url: 127.0.0.1
  port: 11111
  isEnableEncrypt: true
  pwd: 983528987fuck.
  exclusionCodesWhenSnapshot:
    - LIST1983
    - Fund
    - GEM
    - HSCEI Stock
    - HSI Constituent Stocks
    - Hong Kong Index
    - LIST10001
    - LIST1352
    - LIST1600
    - LIST1607
    - LIST1902
    - LIST1910
    - LIST1911
    - LIST1912
    - LIST1921
    - LIST1981
    - LIST1989
    - LIST1990
    - LIST20860
    - LIST20861
    - LIST20862
    - LIST23405
    - LIST23406
    - LIST91331
    - LIST91332
    - LIST91333
    - LIST9700
    - Motherboard