server:
  port: 9091
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/quantx_sub
#    username: postgres
#    password: 123456
#  liquibase:
#    change-log: classpath:db/liquibase-changelog.xml
ft:
  url: 127.0.0.1
  port: 11111
  isEnableEncrypt: true
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl