POST http://localhost:9090/base/stocks?current=2&size=10
Content-Type: application/json

{
  "market": 1
}

###
POST http://localhost:9090/base/plates?page=2&limit=10
Content-Type: application/json

{
  "market": 1
}
###

POST http://localhost:9090/base/ipos
