server:
  port: 9091
ck:
  driverClass: com.clickhouse.jdbc.ClickHouseDriver
  url: jdbc:ch://172.21.17.107:8123/quantx
  user: default
  password: 123456
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
